---
requirements: | 
functional:
  - Вывод в виде форматированной таблицы 0.0
  - Принимает данные на вход "sex, age, height, weight,physical activity level". 0.1
  - Выводит количестко нужных продуктов в граммах по формуле расчета БЖУ. 0.2
  - Выводит название продуктов и дни. 0.3
  - Вывод каллорий/БЖУ/соотношение  0.4
  - Выводит разные расчеты для мужчины и женщины при равных параметрах. 0.5
  - Выводит разные расчеты при выборе разных формул расчета. 0.6 
  - Входит в программу из консоли по команде "split-my-eat" 0.7  
  - Выводит количество каллорий при выборе "calories" 0.8  
  - Выводит дни,продукты и их количество  при выборе "meal plan" 0.9 
  - Выводит калории,дни,продукты и их количество  при выборе "calories and meal plan" 0.10  
  - Выходит из программы при выборе "exit" 0.11 
  - Выводит данные с выбором "1-3 light activities per week" 0.12 
  - Выводит данные с выбором "3-5 moderate activities per week" 0.13
  - Выводит данные с выбором "5-6 moderate activities per week" 0.14 
  - Выводит данные с выбором "7 vigorous activities per week" 0.15
  - Выводит данные с выбором "no activity" 0.16
  - Выводит разное количество каллорий, БЖУ и продуктов исходя из количества тренировок 0.17 

non-functional:
  - Выводит граммовку без плавающей запятой. 1.0
  - Выводит выходные данные на английском языке 1.1     
implicit:
  - Названия и значения не выходят за рамки таблицы 2.0
  